VAGRANTFILE_API_VERSION = "2"

abs_file_path = File.symlink?(__FILE__) ? File.realpath(__FILE__) : __FILE__
path = File.dirname(abs_file_path)

require 'yaml'
require path + '/scripts/homestead.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  Homestead.configure(config, YAML::load(File.read(path + '/Homestead.yaml')))
end
